config/routes.rb
Rails.application.routes.draw do
  resources :manuscripts do
    resources :quires, only: [ :create, :new, :destroy ]
  end

  post 'manuscripts/:manuscript_id/create_quires' => 'bulk_quires#create', as: 'create_quires'

  get 'manuscripts/xml/:id', to: 'manuscripts#export_xml', as: 'manuscript_xml'

  put 'manuscripts/:manuscript_id/leaves/:id/renumber' => 'numberings#update', as: 'update_numbering'

  devise_for :users
  root to: 'manuscripts#index'

  resources :quires, only: [ :edit, :show, :update ]

  resources :leaves, only: [ :destroy ]

  get 'welcome/index'

end

app/models/manuscript.rb
require 'ostruct'

class Manuscript < ActiveRecord::Base
  has_many :quires, -> { order('position ASC') }, dependent: :destroy
  has_many :leaves, -> { order 'quires.position, position' }, through: :quires

  attr_accessor :quire_number_input
  attr_accessor :leaves_per_quire_input
  attr_accessor :skips

  after_save :create_quires

  validates_presence_of :title, :shelfmark

  ##
  # Return the last quire persisted to the database. Quire is eager loaded.
  def last_saved_quire
    quires.includes(:leaves).where.not(id: nil).last
  end

  ##
  # Return the last leaf of the last save quire; otherwise, return `nil`.
  #
  def last_saved_leaf
    q = last_saved_quire
    q.leaves.last if q.present?
  end

  ##
  # Return the folio_number of the `last_saved_leaf`.
  delegate :folio_number, to: :last_saved_leaf, prefix: true, allow_nil: true

  def last_saved_folio_number
    return 0 if quires.empty?
    return 0 if leaves.empty?
    last_saved_leaf_folio_number
  end

  def to_xml options={}
    case options[:xml_type]
    when :filled_quires
      filled_quires_xml.to_xml
    else
      build_xml.to_xml
    end
  end

  def to_struct
    s = OpenStruct.new title: title, shelfmark: shelfmark, url: url, quires: []
    quires.each do |q|
      s.quires << q.to_struct
    end
    s
  end

  ##
  # This returns the 'Joins XML'
  def build_xml
    struct = to_struct
    binding.pry
    Nokogiri::XML::Builder.new do |xml|
      xml.manuscript(url: struct.url) {
        xml.title struct.title
        xml.shelfmark struct.shelfmark
        xml.quires {
          struct.quires.each do |q|
            xml.quire(n: q.n) {
              q.units.each do |u|
                xml.unit {
                  u.leaves.each do |leaf|
                    xml.leaf leaf.to_h
                  end
                } # xml.unit
              end
            } # xml.quire
          end
        } # xml.quires
      } # xml.manuscript
    end
  end

  ##
  # This returns the 'leaves XML'
  def filled_quires_xml
    Nokogiri::XML::Builder.new do |xml|
      xml.manuscript {
        xml.url url
        xml.title title
        xml.shelfmark shelfmark
        quires.each do |q|
          xml.quire(n: q.position) {
            q.filled_quire.each do |leaf|
              xml.leaf leaf.marshal_dump
            end
          }
        end
      }
    end
  end

  def show_attribures
    logger.info "=== #{self.quire_number_input} === #{self.leaves_per_quire_input} ==="
  end

  ##
  # Return an array of ids of leaves preceded by numerical skips. An empty
  # array is returned if no skips are found.
  #
  # For example, for
  #
  #   Leaf id:  3164,  folio_number: 1
  #   Leaf id:  3165,  folio_number: 2
  #   Leaf id:  3166,  folio_number: 3
  #   Leaf id:  3167,  folio_number: 4
  #   Leaf id:  3168,  folio_number: 5
  #   Leaf id:  3169,  folio_number: 7 # <= preceding number is skipped
  #   Leaf id:  3170,  folio_number: 8
  #   Leaf id:  3171,  folio_number: 9
  #
  #  the array `[3169]` is returned because the expected preceding folio
  #  number, `6`, is not used.
  #
  # Non-numerical folio numbers are ignored. For example, for
  #
  #   Leaf id:  3164,  folio_number: 1
  #   Leaf id:  3165,  folio_number: 2
  #   Leaf id:  3166,  folio_number: 3
  #   Leaf id:  3167,  folio_number: 4
  #   Leaf id:  3168,  folio_number: 4a
  #   Leaf id:  3169,  folio_number: 4b
  #   Leaf id:  3170,  folio_number: 5
  #   Leaf id:  3171,  folio_number: 6
  #
  #  the empty array `[]` is returned because numbers '4a' and '4b' are
  #  ignored.
  #
  # If the folio number 1 is not used, this also caught. For example, for
  #
  #   Leaf id:  3165,  folio_number: 3 <= preceding number is skipped
  #   Leaf id:  3166,  folio_number: 4
  #   Leaf id:  3167,  folio_number: 5
  #   Leaf id:  3168,  folio_number: 6
  #   Leaf id:  3169,  folio_number: 7
  #   Leaf id:  3170,  folio_number: 8
  #   Leaf id:  3171,  folio_number: 9
  #
  # the array `[3165]` is returned because "1" is skipped (as is "2", but the
  # method does not determine intervening missing numbers).
  #
  def leaf_skips
    return skips if skips.present?

    last_leaf = nil
    skips = quires.includes(:leaves).flat_map do |quire|
      quire.leaves.flat_map do |leaf|
        v = []
        begin
          # try to convert folio_number to integer; skip on error
          Integer(leaf.folio_number)

          # use "0", to catch manuscripts that don't start with folio "1"
          comp_number = last_leaf.present? ? last_leaf.folio_number : "0"
          unless comp_number.succ == leaf.folio_number
            v = leaf.id
          end
          last_leaf = leaf
        rescue ArgumentError
          # not a numeric folio_number; skip
        rescue TypeError
          # folio_number is nil; skip
        end
        v
      end
    end
    skips
  end

  def renumber_from start_leaf
    next_num = nil
    quires.includes(:leaves).each do |quire|
      quire.leaves.each do |leaf|
        if leaf == start_leaf
          leaf.folio_number = start_leaf.new_number
          next_num = leaf.folio_number_int + 1
        elsif next_num.present?
          begin
            Integer(leaf.folio_number)
            leaf.folio_number = next_num
            next_num += 1
          rescue ArgumentError, TypeError
            # non-numeric folio number; skip
          end
        end
      end
      quire.save if next_num.present?
    end
  end

  def create_quires
    if quire_number_input.present?
      (1..quire_number_input.to_i).each do |i|
        quires.create
        quires.last.create_leaves leaves_per_quire_input
      end
    end
    self.quire_number_input = nil
    self.leaves_per_quire_input = nil
  end
end

app/controllers/manuscripts_controller.rb
class ManuscriptsController < ApplicationController
  before_action :set_manuscript, only: [:edit, :update, :destroy, :export_xml]
  before_action :set_manuscript_eagerly, only: [:show]

  respond_to :html, :xml

  def index
    @manuscripts = Manuscript.all
    respond_with(@manuscripts)
  end

  def export_xml
    send_data @manuscript.to_xml, filename: xml_file_name, type: 'text/xml'
  end

  def show
    respond_with(@manuscript)
  end

  def new
    @manuscript = Manuscript.new
    respond_with(@manuscript)
  end

  def edit
  end

  def create
    @manuscript = Manuscript.new(manuscript_params)
    @manuscript.save
    respond_with(@manuscript)
  end

  def update
    @manuscript.update(manuscript_params)
    respond_with(@manuscript)
  end

  def destroy
    @manuscript.destroy
    respond_with(@manuscript)
  end

  private
  def xml_file_name
    "#{@manuscript.shelfmark.strip.gsub /\s+/, '_'}.xml"
  end

  def set_manuscript
    @manuscript = Manuscript.find(params[:id])
  end

  def set_manuscript_eagerly
    @manuscript = Manuscript.includes(quires: :leaves).find(params[:id])
  end

  def manuscript_params
    params.require(:manuscript).permit(:title, :shelfmark, :url,
                                       :quire_number_input,
                                       :leaves_per_quire_input,
                                       :text_direction)
  end
end

app/views/manuscripts/_bread_crumbs.html.erb
<%= link_to 'Home', root_path %>
<% unless @manuscript.new_record? -%>
 |
<%= link_to @manuscript.shelfmark, @manuscript %>
<% end -%>

app/views/manuscripts/_form.html.erb
<%= form_for @manuscript, html: { class: "form-horizontal" } do |f| %>

  <% if @manuscript.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize(@manuscript.errors.count, "error") %>.
      </div>
      <ul>
      <% @manuscript.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :title, class: "form-control",
          placeholder: "Manuscript title" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :shelfmark, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :shelfmark, class: "form-control",
          placeholder: "Shelfmark" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :text_direction, class: "col-sm-2 control-label" %>
    <div class="col-sm-2">
      <%= f.select :text_direction, Manuscript::TEXT_DIRECTIONS, {},
                   { class: 'form-control'} %>
    </div>
  </div>

    <% if @manuscript.quires.count > 0 -%>
    <div class="row">
      <div class="col-sm-2">
        <p class="field-label">Number of quires</p>
      </div>
      <div class="col-sm-10">
        <p class="field-value"><%= @manuscript.quires.count %></p>
      </div>
    </div>
  <% else -%>
  <div class="form-group">
      <%= f.label :quire_number_input, "Number of quires",
          class: "col-sm-2 control-label" %>
      <div class="col-sm-2">
        <%= f.select :quire_number_input, (1..200),
          { selected: @manuscript.quire_number_input || 20 },
          { class: "form-control", placeholder: "Number of quires" } %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :leaves_per_quire_input, "Leaves per quire",
      class: "col-sm-2 control-label" %>
      <div class="col-sm-2">
        <%= f.select :leaves_per_quire_input, (0..30).step(2).map(&:itself), {}, { class: "form-control" } %>
      </div>
      <div class="col-sm-8">
        <span class="help-block">
          Default number of leaves per quire; don't worry you can adjust this
          for individual quires later.
        </span>
      </div>
    </div>
  <% end -%>

  <div class="actions">
    <%= f.submit class: "btn btn-default" %>
    <%= link_to 'Cancel', @manuscript, class: 'btn btn-default' %>
  </div>
<% end %>

app/views/manuscripts/_summary.html.erb
<div class="row">
  <div class="col-sm-2">
    <p class="field-label">Title</p>
  </div>
  <div class="col-sm-10">
    <p class="field-value"><%= manuscript.title %></p>
  </div>
</div>

<div class="row">
  <div class="col-sm-2">
    <p class="field-label">Shelfmark</p>
  </div>
  <div class="col-sm-10">
    <p class="field-value"><%= manuscript.shelfmark %></p>
  </div>
</div>

<div class="row">
  <div class="col-sm-2">
    <p class="field-label">URL</p>
  </div>
  <div class="col-sm-10">
    <p class="field-value"><%= manuscript.url %></p>
  </div>
</div>

<div class="row">
  <div class="col-sm-2">
    <p class="field-label">Text direction</p>
  </div>
  <div class="col-sm-10">
    <p class="field-value"><%= manuscript.text_direction_name %></p>
  </div>
</div>

app/views/manuscripts/edit.html.erb
<p><%= render 'bread_crumbs' %></p>

<h1>Edit Manuscript</h1>


<%= render 'form' %>

app/views/manuscripts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Manuscripts</h1>

<p><%= link_to 'New Manuscript', new_manuscript_path, class: 'btn btn-default' %></p>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Shelfmark</th>
      <th>URL</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @manuscripts.each do |manuscript| %>
      <tr>
        <td><%= manuscript.title %></td>
        <td><%= manuscript.shelfmark %></td>
        <td><%= link_to shorten(manuscript.url), manuscript.url %></td>
        <td>
          <%= link_to 'Show', manuscript, class: 'btn btn-default btn-sm' %>
        </td>
        <td>
          <%= link_to 'Edit', edit_manuscript_path(manuscript),
                class: 'btn btn-default btn-sm' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<p><%= link_to 'New Manuscript', new_manuscript_path, class: 'btn btn-default' %></p>

app/views/manuscripts/new.html.erb
<p><%= render 'bread_crumbs' %></p>

<h1>New Manuscript</h1>

<%= render 'form' %>

app/views/manuscripts/show.html.erb
<p id="notice"><%= notice %></p>

<p><%= render 'bread_crumbs' %></p>

<h1>Manuscript: <%= @manuscript.title %></h1>


<div class="row">
  <div class="col-sm-2">
    <p class="field-label">Title</p>
  </div>
  <div class="col-sm-10">
    <p class="field-value"><%= @manuscript.title %></p>
  </div>
</div>

<div class="row">
  <div class="col-sm-2">
    <p class="field-label">Shelfmark</p>
  </div>
  <div class="col-sm-10">
    <p class="field-value"><%= @manuscript.shelfmark %></p>
  </div>
</div>

<div class="row">
  <div class="col-sm-2">
    <p class="field-label">URL</p>
  </div>
  <div class="col-sm-10">
    <p class="field-value">
      <% if @manuscript.url.present? -%>
        <%= link_to shorten(@manuscript.url), @manuscript.url %>
      <% end -%>
    </p>
  </div>
</div>

<div class="row">
  <div class="col-sm-2">
    <p class="field-label">Text direction</p>
  </div>
  <div class="col-sm-10">
    <p class="field-value"><%= @manuscript.text_direction_name %></p>
  </div>
</div>

<p>
  <%= link_to 'Edit', edit_manuscript_path(@manuscript), class: 'btn btn-default' %>
  <%= link_to "Model XML", manuscript_xml_path(@manuscript, format: :xml), class: 'btn btn-default' %>
</p>

<%# TODO: Pull out this junk into separate partials %>
<% if @manuscript.quires.present? -%>
  <h3>Quires</h3>

  <% skips = @manuscript.leaf_skips %>

  <div class="row">
    <div class="col-sm-9">
      <div class="panel-group" role="tablist" aria-multiselectable="true">
        <% @manuscript.quires.each do |quire| -%>

          <div class="panel panel-default">
            <div class="panel-heading" role="tab" id="quire_heading_<%= quire.id %>">
              <div class="row">
              <div class="col-sm-6">
                <h4 class="panel-title">
                  <a class="collapsed" data-toggle="collapse" href="#quire_body_<%= quire.id %>" aria-expanded="false" aria-controls="quire_body_<%= quire.id %>">
                    Quire <%= quire.position %> (<%= quire.leaves.size %> leaves)
                  </a>
                </h4>
              </div>
              <div class="col-sm-2 pull-right">
                <%= link_to 'Edit', edit_quire_path(quire), class: 'btn btn-xs btn-default' %>
                <%= link_to 'x', [ @manuscript, quire ], method: :delete,
                    data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger' %>
              </div>
              </div>
            </div>
            <div id="quire_body_<%= quire.id %>" class="panel-collapse collapse" role="tabpanel" aria-labelledby="quire_heading_<%= quire.id %>">
              <div class="panel-body">
                <% if quire.quire_leaves.present? %>
                    <table class="table">
                      <thead>
                      <th scope="col"><strong>Leaf</strong></th>
                      <th scope="col"><strong>Folio number</strong></th>
                      <th scope="col"><strong>Folio certainty</strong></th>
                      <th scope="col"><strong>Attachment method</strong></th>
                      <th scope="col"><strong>Attachment certainty</strong></th>
                      <th scope="col"><strong>Single</strong></th>
                      <th scope="col"><strong>Quire certainty</strong></th>
                      <th scope="col"><strong>Mode</strong></th>
                      <th scope="col"><strong>Mode certainty</strong></th>
                      <th scope="col"><strong>Subquire</strong></th>
                      <th></th>
                      </thead>
                      <tbody>
                      <% quire.quire_leaves.each do |quire_leaf| %>
                          <tr>
                            <td scope="row"><%= quire_leaf.position %></td>
                            <td scope="row"><%= quire_leaf.folio_number %></td>
                            <td scope="row"><%= certainty_name quire_leaf.folio_number_certainty %></td>
                            <td scope="row"><%= quire_leaf.attachment_method %></td>
                            <td scope="row"><%= certainty_name quire_leaf.attachment_method_certainty %></td>
                            <td scope="row"><%= quire_leaf.leaf_single?.yesno %></td>
                            <td scope="row"><%= certainty_name quire_leaf.quire_certainty %></td>
                            <td scope="row"><%= quire_leaf.leaf_mode %></td>
                            <td scope="row"><%= certainty_name quire_leaf.leaf_mode_certainty %></td>
                            <td scope="row"><%= quire_leaf.subquire %></td>
                            <td scope="row">
                              <% if skips.include?(quire_leaf.leaf_id) %>
                                  <%= form_for quire_leaf.leaf, url: update_numbering_path(@manuscript, quire_leaf.leaf), method: :put, html: {class: 'form-inline', id: "renumber_from_leaf_#{quire_leaf.leaf_id}"} do |f| %>
                                      <%= f.submit 'Renumber from here', class: 'btn btn-primary btn-xs' %>
                                      <div class="form-group">
                                        <%= f.select :new_number, Leaf::FOLIO_NUMBERS, { selected: quire_leaf.leaf.folio_number_int.pred }, { class: 'form-control input-sm'} %>
                                      </div>
                                  <% end %>
                              <% end %>
                            </td>
                          </tr>
                      <% end %>
                      </tbody>
                    </table>
                <% end %>
              </div>
            </div>
          </div>

        <% end -%>
      </div>
    </div>
  </div>

<% end -%>

<div class="row">
&nbsp;
</div>
<div class="row">
  <div class="col-sm-8">
    <%= form_for @manuscript, url: create_quires_path(@manuscript), method: :post, html: { id: "manuscript_#{@manuscript.id}_create_quires", class: 'form-inline' } do |f| %>
    <div class="form-group">
      <%= f.label :quire_number_input, 'Quires', class: "control-label" %>
      <%= f.select :quire_number_input, (1..100), { selected: 20 }, { class: "form-control" } %>
    </div>
    <div class="form-group">
      <%= f.label :leaves_per_quire_input, 'Leaves/quire', class: "control-label"  %>
      <%= f.select :leaves_per_quire_input, (2..30).step(2).map(&:itself), { selected: 8 }, { class: "form-control", style: 'max-width: 80px;' } %>
    </div>
    <div class="form-group">
      <%= f.submit 'Add Quires', class: "btn btn-primary" %>
    </div>
    <% end %>

  </div>
</div>
<div class="row">
&nbsp;
</div>
<div class="row">
&nbsp;
</div>
<div class="row">
&nbsp;
</div>